### ISSUE TITLE
Hide volume snapshot in "Choose custom volume" model

### ISSUE THREAD

**Issue by lijunle** [osamuaoki/incus-ui-canonical#3]
When choose to attach a disk to a container / VM, it opens the "Choose custom volume" model.

![Screenshot 2024-05-16 at 01 24 53](https://github.com/osamuaoki/incus-ui-canonical/assets/1296500/192f17c4-df78-442c-85a3-091498464019)

The model shows the custom volume with its snapshots. I could expect the snapshot should not be shown here. At least, we should hide them by default and provide a checkbox to show snapshots.

![Screenshot 2024-05-16 at 01 25 28](https://github.com/osamuaoki/incus-ui-canonical/assets/1296500/26769a11-2233-483d-99af-27e92368ca33)

Related code here: 

https://github.com/osamuaoki/incus-ui-canonical/blob/059baca770112918f474c3cd3154297f2d4d08a4/src/pages/storage/CustomVolumeSelectModal.tsx#L29-L38

**Comment by osamuaoki** [comment]
Hi,

Thanks for interesting suggestions.

As the README.md page for this repo indicate at https://github.com/osamuaoki/incus-ui-canonical , this is my oneshot activity to package UI part only based on the upstream incus developer Zabby's DEB package build script run by CI script.  The advantage of this is no-download of source during binary package build process which makes it easy to become the official DEB package. (Official package requires source which is buildable without internet access except for the official debian repository.)

UI javascript code itself is from Canonical LXD snap package.  Current Incus developer is doing minimal changes to re-brand it to be used for Incus.

What is needed is package and upload all required javascript packages (most likely node.js based) for building this and package to Debian.  Please consider to do so.

If you need sponsor, I can help.

The first step is take over my effort.  (I can update this repo to point to your repo if it becomes ready.)

Osamu

**Comment by lijunle** [comment]
For this particular size issue, it turns out I need to enable BTRFS quota to show them. Although I am still not satisfied with size it shows (ref size vs. excl. size). It sounds an issue to lxd-ui.

I created a PR #4 to merge lxd-ui 0.8 to debian branch.

**Comment by lijunle** [comment]
Sorry, this one issue is about the snapshot, but the volume size.

**Comment by lijunle** [comment]
Report to https://github.com/canonical/lxd-ui/issues/777
